### PR TITLE
Fixing Edit Account Header

### LINKED ISSUE #543: Update edit account page title

### PR DESCRIPTION
**Pull request by neelismail01**
## Ticket link
Closes #543

## Implementation description
* Changed text in header for page

## Steps to test
1. Visit page at `/edit-account` and verify header is "Edit Account"

## What should reviewers focus on?
* Page header is "Edit Account"

## Checklist
- [ ] My PR name is descriptive and in imperative tense
- [ ] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [ ] I have run the appropriate linter(s)
- [ ] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

### CODE REVIEW

File: frontend/src/components/pages/EditAccountPage.tsx [hunk 1]
```diff
@@ -163,7 +163,7 @@ const EditAccountPage = (): React.ReactElement => {
       {isError && <ErrorModal />}
       <Container maxW="container.xl" align="left" mt={12}>
         <Text mb={2} textStyle="display-large">
-          Account Creation
+          Edit Account
```
Comment (MatoPlus) [inline frontend/src/components/pages/EditAccountPage.tsx:166]:
```suggestion
          Edit Profile
```
Actually this naming could be a bit better?

**Review by MatoPlus — APPROVED** [review]
