### PR TITLE
Error modal

### LINKED ISSUE #234: Error page
Shown whenever backend fails.

Link to design: https://www.figma.com/file/TWJTNWjK75A6VgSisySTLe/?node-id=984%3A19053

### PR DESCRIPTION
**Pull request by briantu**
## Ticket link

Closes #234 

## Implementation description
* Created `ErrorModal.tsx` component under `/src/components/common`
* Added component to all the pages we will be using that require a GraphQL query or mutation

## Steps to test
1. To directly see component, you go to any of the pages where it's mounter and remove the `error` condition

## What should reviewers focus on?
* Code correctness
* Design correctness

## Checklist
- [x] My PR name is descriptive and in imperative tense
- [x] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [x] I have run the appropriate linter(s)
- [x] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

### CODE REVIEW

File: frontend/src/components/common/ErrorModal.tsx [hunk 1]
```diff
@@ -0,0 +1,40 @@
...
+  Text,
+  useBoolean,
+} from "@chakra-ui/react";
+import React from "react";
+
+const ErrorModal = (): React.ReactElement => {
+  const [isOpen, setIsOpen] = useBoolean(true);
+
+  return (
+    <Modal isOpen={isOpen} onClose={setIsOpen.off} isCentered>
```
Comment (sherryhli) [inline frontend/src/components/common/ErrorModal.tsx:18]: I think there are some slight deviations from the designs in padding, but not sure if we need to be pixel-perfect here.

**Review by sherryhli — APPROVED** [review]
LGTM! 🚢

**Review by LenaNguyen — APPROVED** [review]
