### PR TITLE
Update branch mutation query to remove stale signups + unsaved selected branches bug

### LINKED ISSUE #569: When we remove a user from their branch does it also remove their shifts?
This is an unconsidered edge case, we probably should consider removing their signed up shifts and well

action: remove signup ie; removing branch for volunteer is destructive

### PR DESCRIPTION
**Pull request by MatoPlus**
## Ticket link

Closes #569

## Implementation description
* Updated updateUserBranchByEmail mutation such that it deletes stale signups when a volunteer has been removed from the branch
* Fix bug where selected branch state is in consistent when discarding branch edits on user management profile drawer at `admin/users` by resetting selected branches to user branches on closing drawer

## Steps to test
1. got to `admin/users`, when saving volunteer branches on the profile drawer, a new modal appears for the destructive action
2. when removing a branch from user, ensure that all signups for that user regardless of status has been removed
3. If you discard your branch edits the state is now consistent when revisiting the profile drawer

## What should reviewers focus on?
* Correctness
* Look and feel

## Checklist
- [x] My PR name is descriptive and in imperative tense
- [x] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [x] I have run the appropriate linter(s)
- [x] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

### CODE REVIEW

File: frontend/src/components/pages/admin/user/MultiBranchSelector.tsx [hunk 1]
```diff
@@ -67,76 +73,86 @@ const MultiBranchSelector = ({
...
-              rightIcon={<ChevronDownIcon />}
-              width="100%"
-              textAlign="left"
-              _hover={{ bg: colors.background.white }}
-              _active={{ bg: colors.background.white }}
+    <>
+      <DeleteModal
+        body="Volunteer sign ups for removed branches will be permanently deleted."
+        title="Update this volunteer's branches?"
+        confirmText="Change"
```
Comment (sherryhli) [inline frontend/src/components/pages/admin/user/MultiBranchSelector.tsx:80]: I wonder if "Change" could be misunderstood. Perhaps we should use "Confirm", which is a more direct response to the question

**Review by sherryhli — DISMISSED** [review]
Tested and looks good, approving with a small suggestion!

File: frontend/src/components/pages/admin/user/MultiBranchSelector.tsx (hunk 1 above)
Comment (MatoPlus) [reply frontend/src/components/pages/admin/user/MultiBranchSelector.tsx:80]: I think that makes sense

**Review by sherryhli — APPROVED** [review]
